Fix datatype error
Puppet 3.7 on Debian jessie complains:

Error: Failed to apply catalog: Parameter name failed on Package[pam]:
Name must be a String not Array at
/etc/puppet/modules/pam/manifests/init.pp:68

Since libpam0g and libpam-modules are dependencies of libpam-runtime
anyways, removing those and turning the array into a string as requested
by puppet fixes the problem.